---
title: "spagetti"
format: html
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(janitor)
library(ggplot2)
```


```{r}
sharks <- read_excel('SharkIncidents_1950_2022_220302.xlsx')
```

```{r}
temp <- read_csv('SantaBarbara_TEMP_1955-202506.csv')
```

```{r}
glimpse(sharks)
glimpse(temp)
colnames(temp)
```
```{r}

temp_clean <- clean_names(temp_clean) # this did nothing worth a shot
temp_clean <- temp[-(1:44), ]
  
```


```{r}
names(temp_clean)[1] <- "year"
names(temp_clean)[2] <- "month"
names(temp_clean)[3] <- "day"

sharks$Date <- as.Date(sharks$Date)

temp_clean$Date <- make_date(year = temp_clean$year, month = temp_clean$month, day = temp_clean$day)

```

```{r}
glimpse(temp_clean)
glimpse(sharks)
```

```{r}
sharks_temp <- merge(
  sharks, 
  temp_clean[, c("Date", '...6')], 
  by = "Date", 
  all.x = TRUE
)


# rename the new column for clarity
names(sharks_temp)[15] <- "temp_c"

head(sharks_temp)
```

```{r}


ggplot(sharks_temp, aes(x = temp_c, y = 1)) +
  geom_jitter(height = 0.1, width = 0) +
  labs(
    x = "Ocean Temperature (°C)",
    y = "Shark Incidents",
    title = "Shark Attacks vs Ocean Temperature"
  ) +
  theme_minimal()

```

```{r}
ggplot(sharks_temp, aes(y = Mode)) +
  geom_bar() +
  labs(
    x = "Ocean Temperature (°C)",
    y = "Mode",
    title = "Shark Attacks vs Ocean Temperature") +
  theme(axis.text.x = element_text(angle = 30, vjust = 0.5, hjust=1)) 
```

